# Generated by Django 3.1.2 on 2022-06-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc_api', '0004_auto_20220603_1705'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='testtable',
        ),
    ]
