# Generated by Django 3.2.13 on 2022-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_api', '0005_auto_20220603_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='c_rl_nm',
        ),
        migrations.AddField(
            model_name='student',
            name='cl',
            field=models.CharField(db_column='class', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
