# Generated by Django 3.2.13 on 2022-06-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc_api', '0006_auto_20220603_1751'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='users',
        ),
    ]
